package common

const (
	ADMIN string = "administrador"
	USER  string = "usuario"
)

const (
	ErrInvalidAuthHeader          = "INVALID_AUTH_HEADER"
	ErrInvalidToken               = "INVALID_TOKEN"
	ErrDBError                    = "DB_ERROR"
	ErrInsuficientRole            = "INSUFFICIENT_ROLE"
	ErrBadRequest                 = "BAD_REQUEST"
	ErrEmailNotFound              = "EMAIL_NOT_FOUND"
	ErrIncorrectPassword          = "INCORRECT_PASSWORD"
	ErrJWTGenerationError         = "JWT_GENERATION_ERROR"
	ErrJWTStorageError            = "JWT_STORAGE_ERROR"
	ErrTokenAlreadyBlacklisted    = "TOKEN_ALREADY_BLACKLISTED"
	ErrPasswordHashingFailed      = "PASSWORD_HASHING_FAILED"
	ErrJSONBindingFailed          = "JSON_BINDING_FAILED"
	ErrNoPermission               = "NO_PERMISSION"
	ErrInvalidData                = "INVALID_DATA"
	ErrServicesMarshalError       = "SERVICES_MARSHAL_ERROR"
	ErrServicesUnMarshalError     = "SERVICES_UNMARSHAL_ERROR"
	ErrInvalidID                  = "INVALID_ID"
	ErrInvoiceNotFound            = "INVOICE_NOT_FOUND"
	ErrNotFound                   = "NOT_FOUND"
	ErrInvalidPageParam           = "INVALID_PAGE_PARAM"
	ErrInvalidLimitParam          = "INVALID_LIMIT_PARAM"
	ErrLimitTooHigh               = "LIMIT_TOO_HIGH"
	ErrMissingFields              = "MISSING_FIELDS"
	ErrUserNotFound               = "USER_NOT_FOUND"
	ErrInvalidUserID              = "INVALID_USER_ID"
	ErrInvalidRoleID              = "INVALID_ROLE_ID"
	ErrQueryPreparationFailed     = "QUERY_PREPARATION_FAILED"
	ErrUserVerificationFailed     = "USER_VERIFICATION_FAILED"
	ErrRoleVerificationFailed     = "ROLE_VERIFICATION_FAILED"
	ErrRoleNotFound               = "ROLE_NOT_FOUND"
	ErrUserRoleVerificationFailed = "USER_ROLE_VERIFICATION_FAILED"
	ErrUserAlreadyHasRole         = "USER_ALREADY_HAS_ROLE"
	ErrUserRoleUpdateFailed       = "USER_ROLE_UPDATE_FAILED"
	ErrJWTTokenRetrievalFailed    = "JWT_TOKEN_RETRIEVAL_FAILED"
	ErrJWTTokenBlacklistingFailed = "JWT_TOKEN_BLACKLISTING_FAILED"
	ErrQueryFailed                = "QUERY_FAILED"
	ErrErrorGeneratingToken       = "ERROR_GENERATING_TOKEN"
	ErrDatabaseSaveFailed         = "DATABASE_SAVE_FAILED"
	ErrRoleIDRetrievalFailed      = "ROLE_ID_RETRIEVAL_FAILED"
)
